// Route path constants
export const ROUTES = {
  HOME: "/",
  LANDING: "/",
  TUTORIAL: "/tutorial",
  TUTORIAL_TEMPLATE_BUILDER: "/tutorial/template-builder",
  TUTORIAL_GENERATE_QUESTION_FROM_TEMPLATE: "/tutorial/generate-question-from-template",
  TUTORIAL_LINK_DUPLICATE: "/tutorial/link-duplicate",
  TUTORIAL_CREATE_ASSESSMENT_FROM_TEMPLATE: "/tutorial/create-assessment-from-template",
  TUTORIAL_UPLOAD_TO_CANVAS: "/tutorial/upload-to-canvas",
  FOLDER: (id: string) => `/folders/${id}`,
  FOLDER_ROOT: "/folders/root",
  QUESTION_BUILDER: "/question-builder",
  QUESTION_EDIT: (id: string) => `/questions/${id}/edit`,
  TEMPLATE_BUILDER: "/template-builder",
  TEMPLATE_EDIT: (id: string) => `/templates/${id}/edit`,
  ASSESSMENT: (id: string) => `/assessments/${id}`,
  ASSESSMENT_TEMPLATE: (id: string) => `/assessment-templates/${id}`,
  QUESTION_BANK: (id: string) => `/question-banks/${id}`,
  QUESTION_TEMPLATE_BANK: (id: string) => `/question-template-banks/${id}`,
  AUTH_CALLBACK: "/auth/callback",
} as const;
