/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { CollaboratorRole } from './collaboratorRole';

/**
 * Request body for adding a collaborator.
 */
export interface AddCollaboratorRequest {
  email: string;
  role: CollaboratorRole;
}
