/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { CollaboratorRole } from './collaboratorRole';
import type { QuestionTemplateResponse } from './questionTemplateResponse';
import type { ResourceVisibility } from './resourceVisibility';

/**
 * Schema for assessment template with its question templates.
 */
export interface AssessmentTemplateWithQuestionTemplatesResponse {
  id: string;
  owner_id: string;
  folder_id: string;
  title: string;
  description: string | null;
  visibility: ResourceVisibility;
  created_at: string;
  updated_at: string;
  question_templates?: QuestionTemplateResponse[];
  my_role?: CollaboratorRole | null;
}
