/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Metadata for assessment creation from template.
 */
export interface AssessmentMetadata {
  /** Owner ID for the assessment */
  owner_id: string;
  /** Optional folder ID */
  folder_id?: string | null;
  /** Override assessment title (defaults to template title) */
  title?: string | null;
  /** Override assessment description (defaults to template description) */
  description?: string | null;
}
