/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { AssessmentTemplateQuestionTemplateResponseInputDataConfig } from './assessmentTemplateQuestionTemplateResponseInputDataConfig';
import type { EntryFunctionParams } from './entryFunctionParams';
import type { TargetElementResponse } from './targetElementResponse';
import type { TextTemplateType } from './textTemplateType';

/**
 * Schema for a question template within an assessment template, including order.
 */
export interface AssessmentTemplateQuestionTemplateResponse {
  id: string;
  owner_id: string;
  question_type: string;
  question_text_template: string;
  text_template_type: TextTemplateType;
  description?: string | null;
  code: string;
  entry_function: string;
  num_distractors: number;
  output_type: string;
  target_elements: TargetElementResponse[];
  input_data_config?: AssessmentTemplateQuestionTemplateResponseInputDataConfig;
  entry_function_params?: EntryFunctionParams;
  created_at: string;
  updated_at: string;
  order: number;
  added_at: string;
}
