/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { CollaboratorRole } from './collaboratorRole';
import type { MCQResponse } from './mCQResponse';
import type { MRQResponse } from './mRQResponse';
import type { ResourceVisibility } from './resourceVisibility';
import type { ShortAnswerResponse } from './shortAnswerResponse';

/**
 * Schema for assessment with its questions.
 */
export interface AssessmentWithQuestionsResponse {
  id: string;
  owner_id: string;
  folder_id: string;
  title: string;
  description: string | null;
  visibility: ResourceVisibility;
  created_at: string;
  updated_at: string;
  questions?: (MCQResponse | MRQResponse | ShortAnswerResponse)[];
  my_role?: CollaboratorRole | null;
}
