/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Visibility settings for assessments.
 */
export type AssessmentVisibility = typeof AssessmentVisibility[keyof typeof AssessmentVisibility];


export const AssessmentVisibility = {
  private: 'private',
  public: 'public',
} as const;
