/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { MCQData } from './mCQData';

/**
 * Response schema for MCQ question in assessment context.
 */
export interface AssessmentMCQResponse {
  id: string;
  owner_id: string;
  template_id: string | null;
  linked_from_question_id?: string | null;
  question_text: string;
  created_at: string;
  updated_at: string;
  question_type: 'mcq';
  mcq_data: MCQData;
  order: number;
  added_at: string;
}
