/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * User profile returned after registration or GET /auth/me.
 */
export interface AuthUserResponse {
  id: string;
  email: string;
  name: string;
}
