/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Model representing a branch element in the code.
 */
export interface BranchElement {
  /** Type of the code element. */
  type?: string;
  /** Line number where the branch is located. */
  line_number: number;
  /** Condition of the branch. */
  condition: string;
}
