/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { CodeInfo } from './codeInfo';
import type { FormElement } from './formElement';

/**
 * Response model for code analysis. Contains code information and form schema.
 */
export interface CodeAnalysisResponse {
  /** Code structure and elements information */
  code_info: CodeInfo;
  /** List of form elements */
  form_elements: FormElement[];
}
