/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { CollaboratorRole } from './collaboratorRole';
import type { ResourceType } from './resourceType';

/**
 * Response schema for a collaborator entry.
 */
export interface CollaboratorResponse {
  id: string;
  resource_type: ResourceType;
  resource_id: string;
  user_name: string;
  user_email: string;
  role: CollaboratorRole;
  added_at: string;
}
