/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { CodeInfoInput } from './codeInfoInput';
import type { CreateQuestionTemplateRequestInputDataConfig } from './createQuestionTemplateRequestInputDataConfig';
import type { CreateTargetElementRequest } from './createTargetElementRequest';
import type { TextTemplateType } from './textTemplateType';

/**
 * Schema for creating a new question template.
 */
export interface CreateQuestionTemplateRequest {
  question_type: string;
  question_text_template: string;
  text_template_type: TextTemplateType;
  description?: string | null;
  code: string;
  entry_function: string;
  num_distractors: number;
  output_type: string;
  target_elements: CreateTargetElementRequest[];
  input_data_config?: CreateQuestionTemplateRequestInputDataConfig;
  code_info?: CodeInfoInput | null;
}
