/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { TargetElementType } from './targetElementType';
import type { TargetModifier } from './targetModifier';

/**
 * Schema for creating a target element associated with a question template.
 */
export interface CreateTargetElementRequest {
  element_type: TargetElementType;
  id_list: number[];
  name?: string | null;
  line_number?: number | null;
  modifier?: TargetModifier | null;
  argument_keys?: string[] | null;
}
