/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for creating a new assessment template.
 */
export interface CreateAssessmentTemplateRequest {
  folder_id: string;
  title: string;
  description?: string | null;
}
