/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for entry function parameters.
 */
export interface EntryFunctionParams {
  parameters: string[];
  has_var_args?: boolean;
  has_var_kwargs?: boolean;
}
