/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { ExecutionSpecInputData } from './executionSpecInputData';

/**
 * Specification for code execution.
 */
export interface ExecutionSpec {
  /** Name of the entry function to execute */
  entry_function: string;
  /** Input data to pass to the entry function (optional for template generation) */
  input_data?: ExecutionSpecInputData;
}
