/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Input data to pass to the entry function (optional for template generation)
 */
export type ExecutionSpecInputData = { [key: string]: unknown } | null;
