/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for folder tree structure with nested children.
 */
export interface FolderTreeResponse {
  id: string;
  owner_id: string;
  parent_id: string | null;
  name: string;
  description: string | null;
  created_at: string;
  children?: FolderTreeResponse[];
}
