/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { AssessmentResponse } from './assessmentResponse';
import type { AssessmentTemplateResponse } from './assessmentTemplateResponse';
import type { FolderResponse } from './folderResponse';
import type { QuestionBankResponse } from './questionBankResponse';
import type { QuestionTemplateBankResponse } from './questionTemplateBankResponse';

/**
 * Schema for folder with its contents (assessments, templates, and child folders).
 */
export interface FolderWithContentsResponse {
  id: string;
  owner_id: string;
  parent_id: string | null;
  name: string;
  description: string | null;
  created_at: string;
  updated_at: string;
  assessments?: AssessmentResponse[];
  assessment_templates?: AssessmentTemplateResponse[];
  question_banks?: QuestionBankResponse[];
  question_template_banks?: QuestionTemplateBankResponse[];
  folders?: FolderResponse[];
}
