/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { FolderResponse } from './folderResponse';

/**
 * Schema for folder path from root to current folder.
 */
export interface FolderPathResponse {
  path: FolderResponse[];
}
