/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * A form option with its details.
 */
export interface FormOption {
  /** Unique identifier for the form option. */
  id: string;
  /** Display label */
  label: string;
  /** Option value */
  value: unknown;
  /** Description of the form option. */
  description: string;
  /** Id of the option that this option depends on. */
  depends_on?: string | null;
}
