/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { FormOption } from './formOption';

/**
 * A form element with available options.
 */
export interface FormElement {
  /** Type of the form element */
  element_type: string;
  /** Display label for this element */
  label: string;
  /** Help text */
  description?: string | null;
  /** Available options */
  options: FormOption[];
  /** Whether selection is required */
  is_required?: boolean;
}
