/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Model representing a function element in the code.
 */
export interface FunctionElement {
  /** Name of the function. */
  name: string;
  /** Type of the code element. */
  type?: string;
  /** Line number where the function is defined. */
  line_number: number;
  /** List of parameters for the function. */
  parameters: string[];
  /** Indicates if this is a function definition. */
  is_definition: boolean;
}
