/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { GenerateQuestionFromTemplateRequestInputData } from './generateQuestionFromTemplateRequestInputData';

/**
 * Generate question from template (no DB persistence).
 */
export interface GenerateQuestionFromTemplateRequest {
  /** Input data dict for ExecutionSpec */
  input_data: GenerateQuestionFromTemplateRequestInputData;
}
