/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { ExecutionSpec } from './executionSpec';
import type { GenerationOptions } from './generationOptions';
import type { QuestionSpec } from './questionSpec';
import type { TextTemplateType } from './textTemplateType';

/**
 * Request to generate a question template (no DB persistence).
 */
export interface GenerateTemplateRequest {
  /** Algorithm code */
  code: string;
  /** Specifications for code execution */
  execution_spec: ExecutionSpec;
  /** Specifications for the question to be generated */
  question_spec: QuestionSpec;
  /** Options for question generation */
  generation_options: GenerationOptions;
  /** Optional custom question text template.             If not provided, one will be auto-generated. */
  question_text_template?: string | null;
  /** Template type for rendering the question text */
  text_template_type?: TextTemplateType;
}
