/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { AssessmentMetadata } from './assessmentMetadata';
import type { GenerateAssessmentFromTemplateRequestQuestionInputsItem } from './generateAssessmentFromTemplateRequestQuestionInputsItem';

/**
 * Generate assessment from template (with DB persistence).
 */
export interface GenerateAssessmentFromTemplateRequest {
  /** Metadata for the assessment to be created from the template */
  assessment_metadata: AssessmentMetadata;
  /** Array of input_data dicts, in question template order */
  question_inputs: GenerateAssessmentFromTemplateRequestQuestionInputsItem[];
}
