/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { CreateQuestionTemplateRequest } from './createQuestionTemplateRequest';

/**
 * Schema for adding a question template to a question template bank.
 */
export interface InsertQuestionTemplateIntoQuestionTemplateBankRequest {
  question_template: CreateQuestionTemplateRequest;
}
