/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { CreateMCQRequest } from './createMCQRequest';
import type { CreateMRQRequest } from './createMRQRequest';
import type { CreateShortAnswerRequest } from './createShortAnswerRequest';

/**
 * Schema for adding a question to an assessment.
 */
export interface InsertQuestionIntoAssessmentRequest {
  question: CreateMCQRequest | CreateMRQRequest | CreateShortAnswerRequest;
  order?: number | null;
}
