/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { AssessmentWithQuestionsResponse } from './assessmentWithQuestionsResponse';
import type { CodeAnalysisResponse } from './codeAnalysisResponse';
import type { GenerateInputsResponse } from './generateInputsResponse';
import type { Question } from './question';
import type { TemplatePreviewResponse } from './templatePreviewResponse';

export type JobResult = CodeAnalysisResponse | TemplatePreviewResponse | Question | GenerateInputsResponse | AssessmentWithQuestionsResponse;
