/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { JobResult } from './jobResult';

/**
 * Returned by GET /jobs/{job_id} — current status and result when available.
 */
export interface JobStatusResponse {
  job_id: string;
  status: string;
  result?: JobResult | null;
  error?: string | null;
}
