/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Returned immediately when a job is submitted to Nomad.
 */
export interface JobSubmittedResponse {
  job_id: string;
  status_url: string;
}
