/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for linking an existing question template to an assessment template.
 */
export interface LinkQuestionTemplateToAssessmentTemplateRequest {
  question_template_id: string;
  order?: number | null;
}
