/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { ListQuestionTemplateBanksQuestionTemplateBanksGetCollabFilter } from './listQuestionTemplateBanksQuestionTemplateBanksGetCollabFilter';

export type ListQuestionTemplateBanksQuestionTemplateBanksGetParams = {
/**
 * Filter by folder ID
 */
folder_id?: string | null;
/**
 * Filter by collaboration role: all, owned, or shared
 */
collab_filter?: ListQuestionTemplateBanksQuestionTemplateBanksGetCollabFilter;
};
