/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */

export type ListQuestionBanksQuestionBanksGetCollabFilter = typeof ListQuestionBanksQuestionBanksGetCollabFilter[keyof typeof ListQuestionBanksQuestionBanksGetCollabFilter];


export const ListQuestionBanksQuestionBanksGetCollabFilter = {
  all: 'all',
  owned: 'owned',
  shared: 'shared',
} as const;
