/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Model representing a loop element in the code.
 */
export interface LoopElement {
  /** Type of the code element. */
  type?: string;
  /** Line number where the loop is located. */
  line_number: number;
  /** Type of the loop (e.g., for, while). */
  loop_type: string;
  /** Condition of the loop. */
  condition: string;
}
