/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { MRQData } from './mRQData';

/**
 * Response schema for MRQ question.
 */
export interface MRQResponse {
  id: string;
  owner_id: string;
  template_id: string | null;
  linked_from_question_id?: string | null;
  assessment_id?: string | null;
  question_bank_id?: string | null;
  order?: number | null;
  question_text: string;
  created_at: string;
  updated_at: string;
  question_type: 'mrq';
  mrq_data: MRQData;
}
