/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { GenerationOptions } from './generationOptions';
import type { QuestionSpec } from './questionSpec';

/**
 * Schema for question template configuration.
 */
export interface QuestionTemplateConfig {
  code: string;
  question_spec: QuestionSpec;
  generation_options: GenerationOptions;
  entry_function: string;
}
