/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Type of question to generate (mcq, mrq, short_answer)
 */
export type QuestionSpecQuestionType = typeof QuestionSpecQuestionType[keyof typeof QuestionSpecQuestionType];


export const QuestionSpecQuestionType = {
  mcq: 'mcq',
  mrq: 'mrq',
  short_answer: 'short_answer',
} as const;
