/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { QuestionSpecOutputType } from './questionSpecOutputType';
import type { QuestionSpecQuestionType } from './questionSpecQuestionType';
import type { TargetElement } from './targetElement';

/**
 * Specification for the question to be generated.
 */
export interface QuestionSpec {
  /** Target elements in the execution to query */
  target: TargetElement[];
  /** Type of output to generate (list, count, first, last) */
  output_type: QuestionSpecOutputType;
  /** Type of question to generate (mcq, mrq, short_answer) */
  question_type: QuestionSpecQuestionType;
}
