/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { CodeInfoOutput } from './codeInfoOutput';
import type { EntryFunctionParams } from './entryFunctionParams';
import type { QuestionTemplateResponseInputDataConfig } from './questionTemplateResponseInputDataConfig';
import type { TargetElementResponse } from './targetElementResponse';
import type { TextTemplateType } from './textTemplateType';

/**
 * Complete schema for question template responses.
 */
export interface QuestionTemplateResponse {
  id: string;
  owner_id: string;
  question_type: string;
  question_text_template: string;
  text_template_type: TextTemplateType;
  description?: string | null;
  code: string;
  entry_function: string;
  num_distractors: number;
  output_type: string;
  target_elements: TargetElementResponse[];
  input_data_config?: QuestionTemplateResponseInputDataConfig;
  code_info?: CodeInfoOutput | null;
  entry_function_params?: EntryFunctionParams;
  linked_from_template_id: string | null;
  assessment_template_id: string | null;
  question_template_bank_id: string | null;
  order: number | null;
  created_at: string;
  updated_at: string;
}
