/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { AssessmentResponse } from './assessmentResponse';
import type { QuestionBankResponse } from './questionBankResponse';

/**
 * Response schema for question usage information.
 */
export interface QuestionUsageResponse {
  assessments?: AssessmentResponse[];
  question_banks?: QuestionBankResponse[];
}
