/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Lightweight schema for listing question templates.
 */
export interface QuestionTemplateSummaryResponse {
  id: string;
  owner_id: string;
  question_type: string;
  question_text_template: string;
  description?: string | null;
  created_at: string;
  updated_at: string;
}
