/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Type of output to generate (list, count, first, last)
 */
export type QuestionSpecOutputType = typeof QuestionSpecOutputType[keyof typeof QuestionSpecOutputType];


export const QuestionSpecOutputType = {
  list: 'list',
  count: 'count',
  first: 'first',
  last: 'last',
} as const;
