/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for a single question template order item.
 */
export interface QuestionTemplateOrder {
  question_template_id: string;
  order: number;
}
