/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Type of the question (mcq, mrq, short_answer, etc.)
 */
export type QuestionQuestionType = typeof QuestionQuestionType[keyof typeof QuestionQuestionType];


export const QuestionQuestionType = {
  mcq: 'mcq',
  mrq: 'mrq',
  short_answer: 'short_answer',
} as const;
