/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { MRQData } from './mRQData';

/**
 * Response schema for MRQ question in question bank context.
 */
export interface QuestionBankMRQResponse {
  id: string;
  owner_id: string;
  template_id: string | null;
  linked_from_question_id?: string | null;
  question_text: string;
  created_at: string;
  updated_at: string;
  question_type: 'mrq';
  mrq_data: MRQData;
  added_at: string;
}
