/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Question types supported by the system.
 */
export type QuestionType = typeof QuestionType[keyof typeof QuestionType];


export const QuestionType = {
  mcq: 'mcq',
  mrq: 'mrq',
  short_answer: 'short_answer',
} as const;
