/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { AssessmentTemplateResponse } from './assessmentTemplateResponse';
import type { QuestionTemplateBankResponse } from './questionTemplateBankResponse';

/**
 * Schema for question template usage information.
 */
export interface QuestionTemplateUsageResponse {
  assessment_templates?: AssessmentTemplateResponse[];
  question_template_banks?: QuestionTemplateBankResponse[];
}
