/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { QuestionTemplateOrder } from './questionTemplateOrder';

/**
 * Schema for reordering question templates in an assessment template.
 */
export interface ReorderQuestionTemplatesInAssessmentTemplateRequest {
  question_template_orders: QuestionTemplateOrder[];
}
