/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { QuestionOrder } from './questionOrder';

/**
 * Schema for reordering questions in an assessment.
 */
export interface ReorderQuestionsInAssessmentRequest {
  question_orders: QuestionOrder[];
}
