/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * URL path segments for collaborable resources, matching existing router prefixes.
 */
export type ResourcePath = typeof ResourcePath[keyof typeof ResourcePath];


export const ResourcePath = {
  assessments: 'assessments',
  'question-banks': 'question-banks',
  'question-template-banks': 'question-template-banks',
  'assessment-templates': 'assessment-templates',
} as const;
