/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Resource types for the generic collaborator table.
 */
export type ResourceType = typeof ResourceType[keyof typeof ResourceType];


export const ResourceType = {
  assessment: 'assessment',
  question_bank: 'question_bank',
  question_template_bank: 'question_template_bank',
  assessment_template: 'assessment_template',
} as const;
