/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Modifiers for target elements.
 */
export type TargetModifier = typeof TargetModifier[keyof typeof TargetModifier];


export const TargetModifier = {
  arguments: 'arguments',
  return_value: 'return_value',
  loop_iterations: 'loop_iterations',
  branch_true: 'branch_true',
  branch_false: 'branch_false',
} as const;
