/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Type of the target element (function, loop, branch, variable)
 */
export type TargetElementTypeProperty = typeof TargetElementTypeProperty[keyof typeof TargetElementTypeProperty];


export const TargetElementTypeProperty = {
  function: 'function',
  loop: 'loop',
  branch: 'branch',
  variable: 'variable',
} as const;
