/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Types of code elements that can be targeted.
 */
export type TargetElementType = typeof TargetElementType[keyof typeof TargetElementType];


export const TargetElementType = {
  function: 'function',
  loop: 'loop',
  branch: 'branch',
  variable: 'variable',
} as const;
