/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { CreateTargetElementRequest } from './createTargetElementRequest';
import type { Question } from './question';
import type { TextTemplateType } from './textTemplateType';

/**
 * Response for template preview.
 */
export interface TemplatePreviewResponse {
  /** Generated template question text */
  question_text_template: string;
  /** Template type */
  text_template_type: TextTemplateType;
  /** Type of question */
  question_type: string;
  /** Code for the question template */
  code: string;
  /** Entry function name */
  entry_function: string;
  /** Output type for the question */
  output_type: string;
  /** Number of distractors for the question */
  num_distractors: number;
  /** Target elements for the question */
  target_elements: CreateTargetElementRequest[];
  /** Preview with placeholders */
  preview_question: Question;
}
