/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Template types for question text templates.
 */
export type TextTemplateType = typeof TextTemplateType[keyof typeof TextTemplateType];


export const TextTemplateType = {
  basic: 'basic',
  mustache: 'mustache',
} as const;
