/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { CodeInfoInput } from './codeInfoInput';
import type { CreateTargetElementRequest } from './createTargetElementRequest';
import type { TextTemplateType } from './textTemplateType';
import type { UpdateQuestionTemplateRequestInputDataConfig } from './updateQuestionTemplateRequestInputDataConfig';

/**
 * Schema for updating a question template.
 */
export interface UpdateQuestionTemplateRequest {
  question_type?: string | null;
  question_text_template?: string | null;
  text_template_type?: TextTemplateType | null;
  description?: string | null;
  code?: string | null;
  entry_function?: string | null;
  num_distractors?: number | null;
  output_type?: string | null;
  target_elements?: CreateTargetElementRequest[] | null;
  input_data_config?: UpdateQuestionTemplateRequestInputDataConfig;
  code_info?: CodeInfoInput | null;
}
