/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { CollaboratorRole } from './collaboratorRole';

/**
 * Request body for updating a collaborator's role.
 */
export interface UpdateCollaboratorRoleRequest {
  role: CollaboratorRole;
}
