/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */

/**
 * Schema for updating a folder.
 */
export interface UpdateFolderRequest {
  name?: string | null;
  description?: string | null;
}
