/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { ResourceVisibility } from './resourceVisibility';

/**
 * Schema for updating an assessment template.
 */
export interface UpdateAssessmentTemplateRequest {
  title?: string | null;
  description?: string | null;
  folder_id?: string | null;
  visibility?: ResourceVisibility | null;
}
