/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * EdCraft Backend API
 * API for EdCraft Backend
 * OpenAPI spec version: 0.1.0
 */
import type { MCQData } from './mCQData';
import type { MRQData } from './mRQData';
import type { QuestionType } from './questionType';
import type { ShortAnswerData } from './shortAnswerData';

/**
 * Schema for updating any question type.
 */
export interface UpdateQuestionRequest {
  question_type?: QuestionType | null;
  question_text?: string | null;
  data?: MCQData | MRQData | ShortAnswerData | null;
}
